# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-PayPal-SDK
version:      0.13
version_from: lib/Business/PayPal/SDK.pm
installdirs:  site
requires:
    Class::Accessor:               0
    Inline:                        0
    Inline::Java:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
